### ISSUE TITLE
`ManyToOneReplacer` slow for small expressions

### ISSUE THREAD

**Issue by parsoyaarihant** [HPAC/matchpy#13]
I have added ~1700 `ReplacementRules` in `ManyToOneReplacer`. The `.replace()` has become very slow even for very small expressions(like `2*x`). 

File: https://github.com/parsoyaarihant/sympy/blob/502fd311d64155560383a5f4f3b2710c318dc410/sympy/integrals/rubi/patterns.py

**Comment by parsoyaarihant** [comment]
Some of the expressions are not matching for long time and I had to close the program.

**Comment by wheerd** [comment]
I will look into it. Apparently no rule can be found that can integrate `2*x`.

Here is what I have tried:
```python
from sympy.integrals.rubi.patterns import rubi_object
from sympy.integrals.rubi.symbol import VariableSymbol, Integer
from sympy.integrals.rubi.operation import Mul, Int

x = VariableSymbol('x')
subject = Int(Mul(Integer(2), x), x)
rubi = rubi_object()
print(rubi.replace(subject))
```
Not sure if that is the right approach. I wanted to focus on the pattern matching and avoid using sympy expressions.

**Comment by parsoyaarihant** [comment]
> Apparently no rule can be found that can integrate 2*x.

Better to use ` rubi_integrate` function(using sympy objects), it will sperate out the constant and then apply the rules. You can try integrating `x` with `rubi_object`.

There is also significant increase in loading time of rules. Will that be fixed after code generation?

**Comment by wheerd** [comment]
One thing you could try is use the sympy expressions directly as in the code I posted on Gitter. Then you don't need to translate back and forth between the two representations. I still have to test that the code generation actually works correctly for more than one pattern, but for single patterns it now covers the full feature set. I will likely complete the code generation tomorrow, then you can try it out with the rubi rules. I think the generated python files might become very big though.

**Comment by parsoyaarihant** [comment]
https://gist.github.com/wheerd/b57efd0dba2dbdba4bc10ff6e71cf5ab#gistcomment-2157131

**Comment by parsoyaarihant** [comment]
How to use `Wildcard.optional()` with `class WC` defined [here](https://gist.github.com/wheerd/b57efd0dba2dbdba4bc10ff6e71cf5ab#file-matchpy_with_sympy-py)

**Comment by wheerd** [comment]
I updated the `WC` class to include the optional parameter. I should turn the `dot`, `optional` etc. into class methods instead of static ones I guess.

**Comment by parsoyaarihant** [comment]
Thanks!
What is the right way to use `ReplacementRule`? This code isn't returning anything:
```python

m_ = WC(1, True, 'm', 1)
a, b, x = symbols('a b x')

subject = x
pattern = Pattern(x**m_)
rule = ReplacementRule(pattern, lambda m: x**(m + 1))

print(replace_all(subject, [rule]))
```

**Comment by wheerd** [comment]
This does not terminate because your replacement is matched again and again growing the exponent to infinity. If you specify `max_count`, then you will get the expected result:
```python
>>> print(replace_all(subject, [rule], max_count=1))
x**2
```

**Comment by parsoyaarihant** [comment]
Thanks!

**Comment by parsoyaarihant** [comment]
I am unable to add new rules to `ManyToOneReplacer`:
```python
import matchpy
Pattern, ReplacementRule, ManyToOneReplacer = matchpy.Pattern, matchpy.ReplacementRule, matchpy.ManyToOneReplacer

from matchpy import replace_all, is_match, Wildcard
from sympy.integrals import Integral
from sympy import Symbol, Pow, cacheit
from matchpy.expressions.functions import register_operation_iterator, register_operation_factory
from matchpy import Operation, CommutativeOperation, AssociativeOperation, OneIdentityOperation

class WC(Wildcard, Symbol):
    def __init__(self, min_length, fixed_size, variable_name=None, default=None, **assumptions):
        Wildcard.__init__(self, min_length, fixed_size, variable_name, default)

    def __new__(cls, min_length, fixed_size, variable_name=None, default=None, **assumptions):
        cls._sanitize(assumptions, cls)
        return WC.__xnew__(cls, min_length, fixed_size, variable_name, default, **assumptions)

    def __getnewargs__(self):
        return (self.min_length, self.fixed_size, self.variable_name, self.optional)

    @staticmethod
    @cacheit
    def __xnew__(cls, min_length, fixed_size, variable_name=None, default=None, **assumptions):
        obj = Symbol.__xnew__(cls, variable_name, **assumptions)
        return obj

    def _hashable_content(self):
        return super()._hashable_content() + (self.min_count, self.fixed_size, self.variable_name, self.optional)

Operation.register(Integral)
register_operation_iterator(Integral, lambda a: (a._args[0],) + a._args[1], lambda a: len(a._args))

Operation.register(Pow)
OneIdentityOperation.register(Pow)
register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))

m_ = WC(1, True, 'm')
x_ = WC(1, True, 'x')
x = Symbol('x')
m = Symbol('m')

pattern1 = Pattern(Integral(x_**m_, x_))
rule1 = ReplacementRule(pattern1, lambda x, m: x**(m + 1)/(m + 1))

subject = Integral(x**2, x)
print(replace_all(subject, [rule1]))

rubi = ManyToOneReplacer()
rubi.add(rule1)
```
returns:
```python
x**3/3
Traceback (most recent call last):
  File "r.py", line 49, in <module>
    rubi.add(rule1)
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/matching/many_to_one.py", line 773, in add
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/matching/many_to_one.py", line 367, in add
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/matching/many_to_one.py", line 386, in _internal_add
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 127, in rename_variables
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 127, in <listcomp>
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 128, in rename_variables
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 171, in create_operation_expression
TypeError: __new__() got an unexpected keyword argument 'variable_name'
```

**Comment by wheerd** [comment]
You will need to register a custom factory for the operation. It is needed in order to construct new expression with that operations, e.g. when the operation is associative and some operands need to be wrapped with it. You can define the factory like this:
```python
def sympy_op_factory(old_operation, new_operands, variable_name):
     return type(old_operation)(*new_operands)

register_operation_factory(Basic, sympy_op_factory)
```
All MatchPy expressions can have a `variable_name`, i.e. you can assign a more complex term to a variable. Mathematica also supports this (e.g. `x: f[_, a]`).

**Comment by parsoyaarihant** [comment]
Error while adding new rule in `ManyToOneReplacer`(While using `WC`(with optional values) with `And` Operator).

### Code
```python
import matchpy
Pattern, ReplacementRule, ManyToOneReplacer = matchpy.Pattern, matchpy.ReplacementRule, matchpy.ManyToOneReplacer

from matchpy import replace_all, is_match, Wildcard, CustomConstraint
from sympy.integrals import Integral
from sympy import Symbol, Pow, cacheit, Basic, Add, Mul, S
from matchpy.expressions.functions import register_operation_iterator, register_operation_factory
from matchpy import Operation, CommutativeOperation, AssociativeOperation, OneIdentityOperation

class WC(Wildcard, Symbol):
    def __init__(self, min_length, fixed_size, variable_name=None, default=None, **assumptions):
        Wildcard.__init__(self, min_length, fixed_size, variable_name, default)

    def __new__(cls, min_length, fixed_size, variable_name=None, default=None, **assumptions):
        cls._sanitize(assumptions, cls)
        return WC.__xnew__(cls, min_length, fixed_size, variable_name, default, **assumptions)

    def __getnewargs__(self):
        return (self.min_length, self.fixed_size, self.variable_name, self.optional)

    @staticmethod
    def __xnew__(cls, min_length, fixed_size, variable_name=None, default=None, **assumptions):
        obj = Symbol.__xnew__(cls, variable_name, **assumptions)
        return obj

    def _hashable_content(self):
        return super()._hashable_content() + (self.min_count, self.fixed_size, self.variable_name, self.optional)

Operation.register(Integral)
register_operation_iterator(Integral, lambda a: (a._args[0],) + a._args[1], lambda a: len((a._args[0],) + a._args[1]))

Operation.register(Add)
OneIdentityOperation.register(Add)
CommutativeOperation.register(Add)
AssociativeOperation.register(Add)
register_operation_iterator(Add, lambda a: a._args, lambda a: len(a._args))

Operation.register(Mul)
OneIdentityOperation.register(Mul)
CommutativeOperation.register(Mul)
AssociativeOperation.register(Mul)
register_operation_iterator(Mul, lambda a: a._args, lambda a: len(a._args))

def sympy_op_factory(old_operation, new_operands, variable_name):
     return type(old_operation)(*new_operands)

register_operation_factory(Basic, sympy_op_factory)

x_ = WC(1, True, 'x')

rubi = ManyToOneReplacer()

pattern7 = Pattern(Integral(Add(Mul(WC(1, True, 'd', S('1')), x_), Mul(WC(1, True, 'b', S('1')), x_)), x_))
rule7 = ReplacementRule(pattern7, lambda x, b, d : b)
rubi.add(rule7)
```
### Error:
```python
Traceback (most recent call last):
  File "r1.py", line 55, in <module>
    rubi.add(rule7)
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/matching/many_to_one.py", line 773, in add
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/matching/many_to_one.py", line 367, in add
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/matching/many_to_one.py", line 386, in _internal_add
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 127, in rename_variables
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 127, in <listcomp>
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 128, in rename_variables
  File "/Users/parsoyaarihant/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev51+ge514171-py3.6.egg/matchpy/expressions/functions.py", line 166, in create_operation_expression
  File "r1.py", line 45, in sympy_op_factory
    return type(old_operation)(*new_operands)
  File "/Users/parsoyaarihant/sympy/sympy/core/operations.py", line 41, in __new__
    c_part, nc_part, order_symbols = cls.flatten(args)
  File "/Users/parsoyaarihant/sympy/sympy/core/add.py", line 264, in flatten
    _addsort(newseq)
  File "/Users/parsoyaarihant/sympy/sympy/core/add.py", line 19, in _addsort
    args.sort(key=_args_sortkey)
  File "/Users/parsoyaarihant/sympy/sympy/core/basic.py", line 193, in compare
    c = l.compare(r)
  File "/Users/parsoyaarihant/sympy/sympy/core/basic.py", line 195, in compare
    c = (l > r) - (l < r)
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by parsoyaarihant** [comment]
@wheerd , ping.

**Comment by wheerd** [comment]
I am not sure what the problem is here. It looks to me like it has something to do with sympy caching again.
It might also be an issue with sympy itself.

**Comment by parsoyaarihant** [comment]
Yes, I too think the same since the full code for `compare` is 
```python
        st = self._hashable_content()
        ot = other._hashable_content()
        c = (len(st) > len(ot)) - (len(st) < len(ot))
        if c:
            return c
        for l, r in zip(st, ot):
            l = Basic(*l) if isinstance(l, frozenset) else l
            r = Basic(*r) if isinstance(r, frozenset) else r
            if isinstance(l, Basic):
                c = l.compare(r)
            else:
                c = (l > r) - (l < r)
            if c:
                return c
```

**Comment by wheerd** [comment]
Oh, I guess I know what the problem is: Some parts of the `_hashable_content` of `WC` can be `None`, e.g. the variable name or the optional information. I am thinkining that `None` should be fine there and `compare` should account for that.

**Comment by parsoyaarihant** [comment]
```python
    def _hashable_content(self):
        return super()._hashable_content() + (self.min_count, self.fixed_size, self.variable_name, self.optional)

```
is returning `None` for `self.optional`. That is causing this error.

**Comment by wheerd** [comment]
An option could be to use tuples with different lengths and just leave the `optional` out if it is `None`.

**Comment by parsoyaarihant** [comment]
@wheerd , you have given the code generation snippet for Rubi. However, I have change the structure of Rubi by using SymPy symbols. Can you guide me on what change do I need to make to [this](https://gist.github.com/wheerd/13ac5a0e9b560db6201d96136fa0bbcc) in order to make it work for new code. 

I am using only `CustomConstraint` for constraints and no MatchPy operators.

**Comment by wheerd** [comment]
@parsoyaarihant I will look at it as soon as I find some time, hopefully this evening. I'm currently traveling so I cannot promise anything. You want to override some more of the methods to customize it. I have to change the code generation so that it is viable for your case anyways, because the file would likely be far to big to work.

**Comment by wheerd** [comment]
I have run into a couple of bugs in the code generation while testing the new rubi rules. I will let you know once I get them fixed.

**Comment by parsoyaarihant** [comment]
Alright

**Comment by wheerd** [comment]
@parsoyaarihant Oh btw, I am noticing that some of the patterns have `int` default values. That causes problems when you use `FreeQ` on them because they are not sympy expressions.

**Comment by wheerd** [comment]
NVM, I am realizing that this is a problem with the code generation because `repr(S(1)) == '1'`.

**Comment by parsoyaarihant** [comment]
Yes, I realised that, I have fixed this issue in my latest commit.

**Comment by parsoyaarihant** [comment]
if you use my branch of sympy, I have found a way to print normal integers as `S()`.
```python
>>> from sympy import sstr
>>> from sympy import S
>>> sstr(S(3), sympy_integers=True)
'S(3)'
```
You can install sympy from my branch and use `sstr` instead of `repr`

**Comment by wheerd** [comment]
Alright, I finally got it working. I have updated the [gist](https://gist.github.com/wheerd/13ac5a0e9b560db6201d96136fa0bbcc). The problem with the large file crashing the interpreter still exists. But I will try to find a workaround for that in the next days.

**Comment by Shekharrajak** [comment]
I have one query on lines similar to this : 

```
Operation.register(Pow)
OneIdentityOperation.register(Pow)
register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))
```

I understood that `Operation.register(Pow)` making `Pow` subclass of `Operation` and same thing happend for `OneIdentityOperation` and `Pow`.

But I didn't understand the use of `register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))` , can someone please help me to understand it ? @parsoyaarihant @wheerd 

Thanks!

**Comment by henrik227** [comment]
To use an operation, MatchPy must be able to access the arguments of this operation, as well as the number of arguments. With `register_operation_iterator`, one can tell MatchPy how to do that.

Just so you now, this is done differently now in MatchPy v0.5.0. See https://github.com/HPAC/matchpy/pull/40.

**Comment by Shekharrajak** [comment]
Thanks @henrik227 , for letting me know these points!

**Comment by Shekharrajak** [comment]
@henrik227 , also can you please let me know what will be the new API/syntax for new version to use an operation ?

**Comment by henrik227** [comment]
There is an example in https://github.com/HPAC/matchpy/pull/40. We use [singledispatch](https://docs.python.org/3.6/library/functools.html?highlight=singledispatch#functools.singledispatch) now. As an example, a function that returns the operands for `dict` is registered as follows:
```
@op_iter.register(dict)
def _(operation):
    return iter(operation.items())
```
For the number of operands, use `@op_len.register(fun)`.

**Comment by Shekharrajak** [comment]
Thanks, @henrik227! So If I want to replace these lines:

```
Operation.register(Pow)
OneIdentityOperation.register(Pow)
register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))

```

then I should write these : 

```
Operation.register(Pow)
OneIdentityOperation.register(Pow)

register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))

@op_iter.register(Pow)
def _(operation):
    return iter(operation._args)

@op_len.register(Pow)
def _(operation):
    return len(operation._args)

```

Please correct me if I am wrong @henrik227 ?

**Comment by henrik227** [comment]
You don't need `register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))` anymore. Other than that, it looks reasonable.

**Comment by Shekharrajak** [comment]
Thanks @henrik227 ! Can you please also let me know how I can verify it (means it will work correctly or not -- an example). I read the examples given [here](https://matchpy.readthedocs.io/en/latest/example.html), but it is only creating a new Operation object.

**Comment by henrik227** [comment]
I would say the simplest thing is to just construct some patterns and subjects using this operation and check if matching behaves the way you would expect it to behave. We do this in our tests, but it's probably simpler to do this manually, for example as described in the [readme](https://github.com/HPAC/matchpy/blob/master/README.rst).

**Comment by Shekharrajak** [comment]
Thanks @henrik227
