### ISSUE TITLE
Repeated definition of the same CustomConstraint

### ISSUE THREAD

**Issue by Upabjojr** [HPAC/matchpy#27]
In the current RUBI rules patterns in SymPy, the same constraint is defined many times. For example: `CustomConstraint(lambda a, x: FreeQ(a, x))` has its definition repeated more and more, like in:

https://github.com/sympy/sympy/blob/628286fb5cc2248002bb0b141a911757a2e81fa7/sympy/integrals/rubi/rules/miscellaneous_algebraic.py#L22

and in the next rule the same constraint is redefined:
https://github.com/sympy/sympy/blob/628286fb5cc2248002bb0b141a911757a2e81fa7/sympy/integrals/rubi/rules/miscellaneous_algebraic.py#L26

Python defines a new object for every new _lambda_ definition, even if the functions return the same identical value.

Does this practice have some potential negative consequences, like:

- the size of the generated decision tree?
- the overall speed of MatchPy?

**Comment by wheerd** [comment]
It will have a negative impact on the overall speed because equivalent constraints will be checked multiple times. It is easy to fix that though by creating a custom subclass of `Constraint` and overriding `__eq__`. I would at least do that for `FreeQ`. You could also create only one representation for each unique constraint during the transformation from the original Rubi rules.

**Comment by parsoyaarihant** [comment]
>  You could also create only one representation for each unique constraint during the transformation from the original Rubi rules. 

Can you give an example? I am unable to understand what exactly you are trying to say here.

**Comment by wheerd** [comment]
Instead of
```python
pattern456 = Pattern(..., CustomConstraint(lambda a, x: FreeQ(a, x)))
```
you would write
```python
constraint123 = CustomConstraint(lambda a, x: FreeQ(a, x))
...
pattern456 = Pattern(..., constraint123)
```
Then you can reuse `constraint123` for every occurence of that constraint.

**Comment by parsoyaarihant** [comment]
Okay, I think I should also redefine `cons()` Constraint class which I was using previously. so there is no dependency on `lambda` functions at all. 

Another question: Does `lambda` causes reduction of speed when loading rules?

**Comment by wheerd** [comment]
I don't think so, but I am not quite sure what you mean. Getting rid of the lambdas also means you can pickle the matcher so you don't have to reconstruct it every time.

**Comment by Upabjojr** [comment]
> Getting rid of the lambdas also means you can pickle the matcher so you don't have to reconstruct it every time.

I like this idea.

**Comment by parsoyaarihant** [comment]
`lambda` functions are also present in `ReplacementRule` hence the rule is unable to pickle.

```python
    pickle.dump(a, fileObject)
AttributeError: Can't pickle local object 'linear_products.<locals>.<lambda>'
```

**Comment by parsoyaarihant** [comment]
I was trying to pickle only thie rule:
```python
    pattern1 = Pattern(Integral(1/x_, x_))
    rule1 = ReplacementRule(pattern1, lambda x : log(x))
    rubi.add(rule1)
```

**Comment by wheerd** [comment]
Yes, you can either use a proper function or use the `dill` package.

**Comment by parsoyaarihant** [comment]
@wheerd  can you give an example of using a function in `ReplacementRule`? I was unable to find this in the documentation.

**Comment by wheerd** [comment]
Just use it instead of the lambda.

**Comment by parsoyaarihant** [comment]
It does not work: 
### Code:
```python
from sympy.integrals.rubi.symbol import WC
from sympy.integrals.rubi.utility_function import FreeQ, NonzeroQ
from matchpy import (Operation, CommutativeOperation, AssociativeOperation,
    ManyToOneReplacer, OneIdentityOperation, CustomConstraint, Pattern, ReplacementRule)
from matchpy.expressions.functions import register_operation_iterator, register_operation_factory
from sympy import Pow, Add, Integral, Basic, Mul, log, S
from sympy.abc import x, m

Operation.register(Integral)
register_operation_iterator(Integral, lambda a: (a._args[0],) + a._args[1], lambda a: len((a._args[0],) + a._args[1]))

Operation.register(Pow)
OneIdentityOperation.register(Pow)
register_operation_iterator(Pow, lambda a: a._args, lambda a: len(a._args))

Operation.register(Add)
OneIdentityOperation.register(Add)
CommutativeOperation.register(Add)
AssociativeOperation.register(Add)
register_operation_iterator(Add, lambda a: a._args, lambda a: len(a._args))

Operation.register(Mul)
OneIdentityOperation.register(Mul)
CommutativeOperation.register(Mul)
AssociativeOperation.register(Mul)
register_operation_iterator(Mul, lambda a: a._args, lambda a: len(a._args))

def sympy_op_factory(old_operation, new_operands, variable_name):
     return type(old_operation)(*new_operands)

register_operation_factory(Basic, sympy_op_factory)

x_ = WC('x')

rubi = ManyToOneReplacer()

pattern1 = Pattern(Integral(S(1)/x_, x_))
rule1 = ReplacementRule(pattern1, lambda x : log(x))
rubi.add(rule1)

pattern2 = Pattern(Integral(x_**WC('m', S(1)), x_), CustomConstraint(lambda m, x: FreeQ(m, x)), CustomConstraint(lambda m: NonzeroQ(m + S(1))))
rule2 = ReplacementRule(pattern2, x**(m + S(1))/(m + S(1)))
rubi.add(rule2)

subject = Integral(x, x)
print(rubi.replace(subject))
```

### Output:
```python
Traceback (most recent call last):
  File "t2.py", line 46, in <module>
    print(rubi.replace(subject))
  File "/Users/arihantparsoya/anaconda/lib/python3.6/site-packages/matchpy-0.5.dev74+gd9efe29-py3.6.egg/matchpy/matching/many_to_one.py", line 797, in replace
TypeError: 'Mul' object is not callable
```

**Comment by wheerd** [comment]
I meant using a Python function:

````python
def replacement(x, m):
    return x**(m + S(1))/(m + S(1))

rule = ReplacementRule(pattern, replacement)
```
