### ISSUE TITLE
ManyToOneMatcher: Position of constraints logic

### ISSUE THREAD

**Issue by Upabjojr** [HPAC/matchpy#41]
This issue regards the discussion at: https://github.com/sympy/sympy/pull/14988

The generated graph of the many-to-one matcher appears like this:
https://drive.google.com/file/d/1s2CewkIWhoUsKrSEE4vly1gOzDudg3Xn/view

In the transition between state 2212 and 2213 the constraint _c0_ appears. It's pretty curious, for two reasons:
- Constraint _c0_ requires two parameters, but at transition 2212->2213 only _i2_ has been read.
- The transition 2212->2213 is also shared by pattern _p0_, which does not have any constraint associated with it.

If you use the code generator, the presence of _c0_ at the transition 2212->2213 produces a wrong decision tree. If I manually remove the constraint _c0_ from that transition, the generated code works fine:
```python
state2212.transitions[None][0].check_constraints.discard(0)
```
At this point, there are two possible fixes:
1. modify the generated code to exactly mimic the way `_Matcher` visits the tree, so that the generated decision tree matches in the correct way.
2. modify the way constraints are added to the transitions, so that transition 2212->2213 would not have _c0_.

I've got the impression that the constraints are being placed in the wrong transitions and somehow `_Matcher` is able to ignore this issue during the tree visit. But maybe I'm wrong, so I open this issue to ask for suggestion.

If it's OK, I will try to fix this issue myself.

**Comment by Upabjojr** [comment]
@wheerd @henrik227 please let me know what you think.

**Comment by henrik227** [comment]
I would try to change how the constraints are added. I don't see why c0 should be at the transition 2212->2213, so to me it looks like a bug.

If you want to try and fix this, please go ahead.

**Comment by wheerd** [comment]
@Upabjojr if I remember correctly, then a constraint on a transition in the tree merely means that this is a constraint that needs re-checking (in case it has all variables set). There can be different sets of variables present at a node for example if an `Alternatives` is used. My guess would be that the generated code is wrong in too aggressively checking constraints.
