### ISSUE TITLE
GPL'd dependency: hopcroftkarp library

### ISSUE THREAD

**Issue by Upabjojr** [HPAC/matchpy#42]
The [hopcroftkarp library](https://github.com/sofiatolaosebikan/hopcroftkarp) upon which this project depends is GPL'd.

I have re-implemented the Hopcroft-Karp algorithm in C++ as part of an attempt to make MatchPy usable in SymEngine (that is, SymPy's core rewritten in C++). I didn't perform extensive testing, so there may be bugs. That code can be translated into Python.

**Comment by henrik227** [comment]
Thank you for letting us know. Indeed, we've been thinking about getting rid of that dependency: https://github.com/HPAC/matchpy/issues/16

Where can we find that code?

**Comment by Upabjojr** [comment]
Sorry, forgot to share the link:
https://github.com/symengine/symengine/blob/9cb6da759fb95e2ffece407e0cf2bad136a3933b/matchpygen/bipartite.h#L126

**Comment by skirpichev** [comment]
@Upabjojr, `hopcroftkarp` library is one-person project.  Maybe you could just convince its author to release code under a more permissive license.  I think, LGPL-3 would be enough.

**Comment by henrik227** [comment]
> @Upabjojr, `hopcroftkarp` library is one-person project. Maybe you could just convince its author to release code under a more permissive license. I think, LGPL-3 would be enough.

Good point.

@sofiatolaosebikan As you may have noticed, MatchPy uses your hopcroftkarp package, and MatchPy in turn may end up being used by some other projects, for example SymPy. If I understand that correctly, it might be a problem for some of those other projects that hopcroftkarp uses the GPLv3 license. Would you be willing to use a more permissive license?

**Comment by sofiatolaosebikan** [comment]
> > @Upabjojr, `hopcroftkarp` library is one-person project. Maybe you could just convince its author to release code under a more permissive license. I think, LGPL-3 would be enough.
> 
> Good point.
> 
> @sofiatolaosebikan As you may have noticed, MatchPy uses your hopcroftkarp package, and MatchPy in turn may end up being used by some other projects, for example SymPy. If I understand that correctly, it might be a problem for some of those other projects that hopcroftkarp uses the GPLv3 license. Would you be willing to use a more permissive license?

@hbarthels: Yes, I would be happy to release the hopcroftkarp library under a licence that would be suitable for all the projects depending on it. I received a similar request from @jvdillon who suggested "MIT Licence" or "Apache 2 Licence". Would any one of these be sufficient?

**Comment by hbarthels** [comment]
> @hbarthels: Yes, I would be happy to release the hopcroftkarp library under a licence that would be suitable for all the projects depending on it. I received a similar request from @jvdillon who suggested "MIT Licence" or "Apache 2 Licence". Would any one of these be sufficient?

Thank you, but we just added an internal implementation of the algorithm to MatchPy with https://github.com/HPAC/matchpy/pull/64, so we don't need the `hopcroftkarp` package anymore.
