### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Upabjojr** [HPAC/matchpy#55]
Hi,

I've seen there were some changes in the way classes are registered. The current SymPy master branch does not support this.

I have added a fixing PR to SymPy: https://github.com/sympy/sympy/pull/16356

It requires a new release of MatchPy in order to be mergeable.

Will there be a new release in the future?

**Comment by Upabjojr** [comment]
Maybe new release after merging: https://github.com/HPAC/matchpy/pull/50

**Comment by wheerd** [comment]
Sound like a good plan, we can make a new release after merging #50. See my comment there.

**Comment by wheerd** [comment]
I just released version [0.5.0](https://github.com/HPAC/matchpy/releases/tag/0.5.0).

**Comment by Upabjojr** [comment]
@wheerd thanks.

Do you know how to update the Anaconda repository as well?
https://anaconda.org/conda-forge/matchpy

**Comment by henrik227** [comment]
That happens over here: https://github.com/conda-forge/matchpy-feedstock/pull/1. Unfortunately, one of the tests is failing right now.
