### ISSUE TITLE
Doubt in `ManyToOneReplacer`

### ISSUE THREAD

**Issue by parsoyaarihant** [HPAC/matchpy#7]
I am wondering what happens when we add two `ReplacementRule` to `ManyToOneReplacer` whose `Pattern` and `Constraint` are same but have different replacement expression?

**Comment by wheerd** [comment]
Because under the hood sets and dicts are used, it is not deterministic which one is found and applied first. The same is true for two distinct patterns that both match. The order is not guaranteed because of the same reason.

**Comment by parsoyaarihant** [comment]
Thanks!

**Comment by wheerd** [comment]
If you are worried that the order of rule applications matters, maybe you can see if the Rubi rules are  [confluent](https://en.wikipedia.org/wiki/Confluence_(abstract_rewriting)) or if they can be made confluent. Then the order in which they are applied, does not matter.
