### ISSUE TITLE
New MatchPy version?

### ISSUE THREAD

**Issue by Upabjojr** [HPAC/matchpy#71]
Hi,

can we have a new MatchPy version in order to definitely have all GPL dependencies removed?

**Comment by hbarthels** [comment]
I just created a new release. Unfortunately, there is a problem with the GitHub actions: https://github.com/HPAC/matchpy/runs/1963370678. I would like to fix that first before uploading the new version to PyPI and conda-forge.
Since he set this up, I've asked @wheerd if he knows what to do about it.

**Comment by hbarthels** [comment]
MatchPy 0.5.4 is now available on PyPI. It will probably take a couple of hours before it's in conda-forge.

**Comment by hbarthels** [comment]
As you may have noticed, there is a problem with uploading the latest version to conda-forge: https://github.com/conda-forge/matchpy-feedstock/pull/6 I don't know what causes this problem, and I also don't know how to fix it.

In general, I think it would make sense to add you to this repository as a maintainer. Would that be ok for you?

**Comment by Upabjojr** [comment]
> In general, I think it would make sense to add you to this repository as a maintainer. Would that be ok for you?

OK.

> As you may have noticed, there is a problem with uploading the latest version to conda-forge: [conda-forge/matchpy-feedstock#6](https://github.com/conda-forge/matchpy-feedstock/pull/6) I don't know what causes this problem, and I also don't know how to fix it.

I'm not familiar with publishing packages to Conda. Maybe @asmeurer can help.

**Comment by hbarthels** [comment]
The latest version is now in conda-forge.
