### ISSUE TITLE
Expression matching with patterns without wildcards

### ISSUE THREAD

**Issue by kaushikcfd** [HPAC/matchpy#74]
```python
import matchpy as m

f = m.Operation.new("f", arity=m.Arity.variadic, commutative=True,
                    associative=True)
a, b, c = m.Symbol("a"), m.Symbol("b"), m.Symbol("c")
expr = f(a, b, c)
matches = m.match_anywhere(expr, m.Pattern(f(a, b)))
print(list(matches))  # prints '[]'
```

In the above snippet `f(a, b)` appears in the expression as `expr` can be realized as `f(f(a, b), c)`, however `match_anywhere` and `replace_all` are unable to find those.

Is this a missing feature or just a wrong usage of the API?

Thanks in advance!

**Comment by kaushikcfd** [comment]
Turns out it isn't quite the wildcard that's the problem, but `match_anywhere` considers only children to be subexpressions. See https://github.com/HPAC/matchpy/blob/45f63748f4f57ed1803df09d2bfc4c7b28008995/matchpy/matching/one_to_one.py#L76-L79.

**Comment by wheerd** [comment]
You should be able to achieve what you want by using `m.Pattern(f(a, b, Wildcard.star()))`. I think this is an edge case, where the matching does not work intuitively.

**Comment by kaushikcfd** [comment]
@wheerd: Thanks for the reply. I think that's fair.

We could consider the combinations of subject's children of a variadic op with the same number of terms as in the pattern, but I guess that might significantly increase the `is_match` invocations.

(Feel free to close this, if you think there's not much that could be improved here.)

**Comment by hbarthels** [comment]
> We could consider the combinations of subject's children of a variadic op with the same number of terms as in the pattern, but I guess that might significantly increase the `is_match` invocations.

I think this is a bit tricky. Formally, given a pattern `s` and a subject `t`, there is a match if there is a substitution `σ` such that `σ(s) = t`. `match_anywhere` tries to find a node in the expression tree where such a substitution exists. Such a node doesn't exist here. As you wrote, it would be possible to rewrite `f(a, b, c)` to `f(f(a, b), c)` and match `f(a, b)`, but in that case it's not clear what the path returned by `match_anywhere` should be. We needed to return something that somehow described how the expression was rewritten.
